/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */


plugins {
    @Suppress("DSL_SCOPE_VIOLATION")
    libs.plugins.kotlin
    @Suppress("DSL_SCOPE_VIOLATION")
    libs.plugins.spotless
    application
}

dependencies {
    implementation(libs.konfig)
}

